# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8af0c47349b492138ea77df33eff13a35c99a2b9b573dc960ef1c150228d086e7d39d42cd5ef6ddbfe264db5572abfe7e7ee4c0d26c0bc14454f254ea85ad6b5

test:
  secret_key_base: 2cd554a8e406d6ba64d4147a03ec884e4f8310f4a99c88e554e09c70fdb80c0ad1027937e6300c08252c3807851fbc89509dd9d78fcf209f6e52ce8909c768cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
